# Generated by Django 2.2.6 on 2019-10-14 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191014_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.DurationField(default=datetime.datetime(2019, 10, 9, 9, 24, 51, 305944)),
        ),
    ]
