# Generated by Django 2.2.6 on 2019-10-14 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191014_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='duration',
        ),
    ]
