# Generated by Django 2.2.6 on 2019-10-14 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_package_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=5)),
        ),
    ]
